name: Build

on:
  push: 
    branches: [ "develop", "main" ]
    
env:
  SOURCE_DIR: ./TestApp

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:  
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: 5.0.x
            
      - name: Restore dependencies
        run: cd ./TestApp && dotnet restore ./TestApp.sln
        
      - name: Build
        run: dotnet build --no-restore
        working-directory: ./TestApp
        
      - name: Test
        run: dotnet test --no-build --verbosity normal  
        working-directory: ./TestApp
