name: Docker

on:
  push: 
    branches: [ "develop", "main" ]
    
env:
  SOURCE_DIR: ./TestApp
  PROJECT_NAME: ./TestApp.sln

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:          
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Install Buildx
        uses: docker/setup-buildx-action@v2.2.1
        
      - name: Buildx Image
        uses: docker/build-push-action@v3.3.0
        

